version: '3.8'
services:
  gogo-db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: 'gogo_db'
      POSTGRES_USER: 'gogo_service'
      POSTGRES_PASSWORD: 'gogo1234'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - gogo-db-volume:/var/lib/postgresql/data
  gogo-api:
    build: ./api
    environment:
      - GOGO_DB_URL=postgres://gogo_service:gogo1234@gogo-db/gogo_db
    depends_on:
      - gogo-db
    ports:
      - '8000:8000'
    expose:
      - '8000'
  gogo-app:
    build: ./app
    depends_on:
      - gogo-api
    ports:
      - '8080:8080'
    expose:
      - '8080'
volumes:
  gogo-db-volume: null
